Repository palantir/docker-compose-rule, pull requests merged in 2019-07, with the labels that each got.

#293 Collect all logs of restarted containers
  README.md
  changelog/@unreleased/pr-293.v2.yml
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/configuration/ShutdownStrategy.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/CallbackThenDelegateShutdownStrategy.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DelegatingDockerCompose.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DockerCompose.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/GracefulShutdownStrategy.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/KillDownShutdownStrategy.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/SkipShutdownStrategy.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/logging/DoNothingLogCollector.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/logging/FileLogCollector.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/logging/LogCollector.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/CallbackThenDelegateShutdownStrategyShould.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/DockerComposeShould.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/GracefulShutdownStrategyShould.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/execution/KillDownShutdownStrategyShould.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/logging/FileLogCollectorShould.java
  docker-compose-rule-junit4/src/main/java/com/palantir/docker/compose/DockerComposeRule.java
  docker-compose-rule-junit4/src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java
Labels: autorelease

#299 Increase timeout and simplify log collection
  changelog/@unreleased/pr-299.v2.yml
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/execution/DefaultDockerCompose.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/logging/FileLogCollector.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/logging/FileLogCollectorShould.java
Labels: autorelease, merge when ready

#300 Re-enable integration tests on master
  docker-compose-rule-junit4/build.gradle
  docker-compose-rule-junit4/src/integrationTest/java/com/palantir/docker/compose/HostNetworkedPortsIntegrationTest.java
Labels: merge when ready, no changelog

#308 Bump hamcrest to 2.1
  docker-compose-rule-core/build.gradle
  docker-compose-rule-junit4/build.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#303 Refactor to centralize implementation in docker-compose-rule-core
  docker-compose-rule-core/build.gradle
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/AggressiveShutdownStrategyIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/AggressiveShutdownWithNetworkCleanupStrategyIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/DockerComposeManagerNativeHealthcheckIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/DockerComposeManagerUpContainerIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/EventsIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/HostNetworkedPortsIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/RemoveConflictingContainersIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/execution/EnvironmentVariableIntegrationTest.java
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/logging/LoggingIntegrationTest.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/DockerComposeManager.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/EventEmitter.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/RecordingCluster.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/RecordingClusterWait.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/events/EventConsumer.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/DockerComposeManagerShould.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/EventEmitterShould.java
  docker-compose-rule-core/src/test/resources/docker-compose.yaml
  docker-compose-rule-core/src/test/resources/environment/docker-compose.yaml
  docker-compose-rule-core/src/test/resources/events/all-good-docker-compose.yaml
  docker-compose-rule-core/src/test/resources/host-networked-docker-compose.yaml
  docker-compose-rule-core/src/test/resources/named-containers-docker-compose.yaml
  docker-compose-rule-core/src/test/resources/shutdown-strategy-with-network.yaml
  docker-compose-rule-core/src/test/resources/shutdown-strategy.yaml
  docker-compose-rule-core/src/test/resources/up-integration-test.yaml
  docker-compose-rule-junit4/build.gradle
  docker-compose-rule-junit4/src/main/java/com/palantir/docker/compose/DockerComposeRule.java
  docker-compose-rule-junit4/src/test/java/com/palantir/docker/compose/DockerComposeRuleShould.java
  docker-compose-rule-junit4/src/test/resources/native-healthcheck.yaml
  versions.lock
Labels: merge when ready, no changelog
