Repository palantir/docker-compose-rule, pull requests merged in 2019-08, with the labels that each got.

#320 Fix master branch
  docker-compose-rule-core/src/integrationTest/java/com/palantir/docker/compose/AggressiveShutdownWithNetworkCleanupStrategyIntegrationTest.java
Labels: merge when ready, no changelog

#322 Add origin git remote url path to reports
  changelog/@unreleased/pr-322.v2.yml
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/reporting/GitUtils.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/reporting/ReportCompiler.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/reporting/GitUtilsTest.java
  docker-compose-rule-events-api/src/main/conjure/report-api.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#323 Bump down conjure java runtime serailization dependency version
  changelog/@unreleased/pr-323.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#324 Clear run recorder data after recording a run to avoid duplicate data
  changelog/@unreleased/pr-324.v2.yml
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/reporting/RunRecorder.java
  docker-compose-rule-core/src/test/java/com/palantir/docker/compose/reporting/RunRecorderTest.java
Labels: autorelease, merge when ready

#304 Add docker-compose-junit-jupiter package
  changelog/@unreleased/pr-304.v2.yml
  docker-compose-junit-jupiter/build.gradle
  docker-compose-junit-jupiter/src/integrationTest/java/com/palantir/docker/compose/DockerComposeExtensionIntegrationTest.java
  docker-compose-junit-jupiter/src/integrationTest/resources/docker-compose.yaml
  docker-compose-junit-jupiter/src/main/java/com/palantir/docker/compose/DockerComposeExtension.java
  settings.gradle
  versions.lock
  versions.props
Labels: merge when ready

#331 Remove duplication by inverting BuilderExtensions control
  docker-compose-junit-jupiter/src/main/java/com/palantir/docker/compose/DockerComposeExtension.java
  docker-compose-rule-core/src/main/java/com/palantir/docker/compose/DockerComposeManager.java
  docker-compose-rule-junit4/src/main/java/com/palantir/docker/compose/DockerComposeRule.java
Labels: merge when ready, no changelog

#332 junit5 DockerComposeExtension should be a @ClassRule equivalent (also docs)
  README.md
  docker-compose-junit-jupiter/src/integrationTest/java/com/palantir/docker/compose/DockerComposeExtensionIntegrationTest.java
  docker-compose-junit-jupiter/src/main/java/com/palantir/docker/compose/DockerComposeExtension.java
Labels: autorelease, merge when ready, no changelog
